### ISSUE TITLE
clerk account

### ISSUE THREAD

**Issue by mberman84** [SawyerHood/tlbrowse#5]
I think you forgot to mention in the instructions that you need a clerk account?

**Comment by SawyerHood** [comment]
Ooops this is a mistake. This should work without a clerk account. I just fixed this so when you run locally you don't need to set up clerk (all of the auth features are disabled). Auth is only there for me to rate limit on the published version.

**Comment by mberman84** [comment]
I recorded a tutorial that will be published to YouTube in the next few days. I’ll mention in the description that Clerk is no longer needed. Thanks for the cool project!

**Comment by SawyerHood** [comment]
@mberman84 let me know if there is anything else I can do for you!
