### ISSUE TITLE
Bun does not work

### ISSUE THREAD

**Issue by steelliberty** [SawyerHood/tlbrowse#6]
Hi .. I tried to do the setup using pycharm. Created environment downloaded the git added the .env.local file and added my claude api_key.  I also installed bun, after attempting bun install.  I was not able to get bun install to work (not found) and bun alone is not found. 

I am not familiar with bun so at this point I am not able to go forward. 

I would like to try the tlbrowse, 

thank you, 
SL

**Comment by SawyerHood** [comment]
You need to install bun here from here: https://bun.sh/

Let me update the readme
